-- FORCE SCHEMA REPAIR (ADVANCED)

-- 1. NOTIFY API to reload schema cache (Fixes 400 Bad Request if cached)
NOTIFY pgrst, 'reload schema';

-- 2. DYNAMICALLY DROP CONSTRAINTS (Fixes 409 Conflict if name mismatches)
DO $$
DECLARE
    r RECORD;
BEGIN
    -- Drop FK from 'tables' referencing 'zones' (zone_id)
    FOR r IN (
        SELECT con.conname
        FROM pg_catalog.pg_constraint con
        INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
        INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
        WHERE nsp.nspname = 'public' AND rel.relname = 'tables' AND con.contype = 'f'
          AND ARRAY[con.conkey[1]] = (
              SELECT ARRAY[attnum] FROM pg_attribute WHERE attrelid = rel.oid AND attname = 'zone_id'
          )
    ) LOOP
        EXECUTE 'ALTER TABLE tables DROP CONSTRAINT ' || quote_ident(r.conname);
    END LOOP;

    -- Drop FK from 'bookings' referencing 'tables' (assigned_table_id)
    FOR r IN (
        SELECT con.conname
        FROM pg_catalog.pg_constraint con
        INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
        INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
        WHERE nsp.nspname = 'public' AND rel.relname = 'bookings' AND con.contype = 'f'
          AND ARRAY[con.conkey[1]] = (
              SELECT ARRAY[attnum] FROM pg_attribute WHERE attrelid = rel.oid AND attname = 'assigned_table_id'
          )
    ) LOOP
         EXECUTE 'ALTER TABLE bookings DROP CONSTRAINT ' || quote_ident(r.conname);
    END LOOP;
END $$;

-- 3. ENSURE COLUMNS EXIST (Fixes 400 Bad Request if missing)
CREATE TABLE IF NOT EXISTS zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  name TEXT, 
  name_es TEXT,
  name_en TEXT,
  "position" INTEGER DEFAULT 0,
  restaurant_id UUID REFERENCES restaurants(id)
);

DO $$
BEGIN
    ALTER TABLE zones ADD COLUMN IF NOT EXISTS name_es TEXT;
    ALTER TABLE zones ADD COLUMN IF NOT EXISTS name_en TEXT;
    ALTER TABLE zones ADD COLUMN IF NOT EXISTS restaurant_id UUID REFERENCES restaurants(id);
END $$;

CREATE TABLE IF NOT EXISTS tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  table_number TEXT,
  zone_id BIGINT REFERENCES zones(id),
  min_pax INTEGER,
  max_pax INTEGER,
  restaurant_id UUID REFERENCES restaurants(id)
);

DO $$
BEGIN
    ALTER TABLE tables ADD COLUMN IF NOT EXISTS restaurant_id UUID REFERENCES restaurants(id);
END $$;

-- 4. RE-APPLY CONSTRAINTS WITH CASCADE/SET NULL
ALTER TABLE tables 
  ADD CONSTRAINT tables_zone_id_fkey_cascade 
  FOREIGN KEY (zone_id) 
  REFERENCES zones(id) 
  ON DELETE CASCADE;

-- Only add if column exists (it should by now)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'assigned_table_id') THEN
      ALTER TABLE bookings 
        ADD CONSTRAINT bookings_assigned_table_id_fkey_setnull 
        FOREIGN KEY (assigned_table_id) 
        REFERENCES tables(id) 
        ON DELETE SET NULL;
  END IF;
END $$;

-- 5. FINAL RELOAD
NOTIFY pgrst, 'reload schema';
