-- DANGER: THIS SCRIPT RESETS ZONES AND TABLES
-- AND UNASSIGNS EXISTING BOOKINGS FROM DELETED TABLES
-- Fixes error: "insert or update on table bookings violates foreign key..."

-- 1. Unlink Bookings (Preserve booking history but detach from tables)
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_table_id_fkey;
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_assigned_table_id_fkey;

-- 2. Drop Tables and Zones completely (Fresh Start)
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS zones CASCADE;

-- 3. Recreate Zones
CREATE TABLE zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  name TEXT, 
  name_es TEXT,
  name_en TEXT,
  "position" INTEGER DEFAULT 0,
  restaurant_id UUID REFERENCES restaurants(id)
);

-- 4. Recreate Tables
CREATE TABLE tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  table_number TEXT,
  zone_id BIGINT REFERENCES zones(id) ON DELETE CASCADE,
  min_pax INTEGER,
  max_pax INTEGER,
  restaurant_id UUID REFERENCES restaurants(id)
);

-- 5. CRITICAL FIX: Unassign orphaned bookings
-- Since we deleted the tables, the old table_ids (e.g., 23) no longer exist.
-- We must set them to NULL so the new constraint doesn't fail.
UPDATE bookings SET assigned_table_id = NULL WHERE assigned_table_id IS NOT NULL;

-- 6. Re-link Bookings (Safe now because references are NULL)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'assigned_table_id') THEN
      ALTER TABLE bookings 
        ADD CONSTRAINT bookings_assigned_table_id_fkey 
        FOREIGN KEY (assigned_table_id) 
        REFERENCES tables(id) 
        ON DELETE SET NULL;
  END IF;
END $$;

-- 7. Enable Security
ALTER TABLE zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all zones" ON zones USING (true);
CREATE POLICY "Enable all tables" ON tables USING (true);

-- 8. Reload Schema Cache
NOTIFY pgrst, 'reload schema';
